//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudies.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabConfiguration
    {
        public LabConfiguration()
        {
            this.Labs = new HashSet<Lab>();
            this.LabSoftwares = new HashSet<LabSoftware>();
        }
    
        public int ID { get; set; }
        public Nullable<int> VM_Count { get; set; }
        public string RAM { get; set; }
        public string Hard_Disk { get; set; }
        public string OS { get; set; }
    
        public virtual ICollection<Lab> Labs { get; set; }
        public virtual ICollection<LabSoftware> LabSoftwares { get; set; }
    }
}
