//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudies.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabSoftware
    {
        public int ID { get; set; }
        public int Config_Id { get; set; }
        public int Software_Id { get; set; }
        public string Software_Path { get; set; }
    
        public virtual LabConfiguration LabConfiguration { get; set; }
        public virtual SoftwareList SoftwareList { get; set; }
    }
}
