//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudies.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Labs = new HashSet<Lab>();
        }
    
        public int ID { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public int Profile_Id { get; set; }
    
        public virtual ICollection<Lab> Labs { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
